# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'tmchat' do
  use_frameworks!
  
  # ignore all warnings from all dependencies
  inhibit_all_warnings!

  pod 'GRDB.swift', '~> 5.26'
  pod 'SQLite.swift', '~> 0.12.0'
  pod 'Starscream', '~> 4.0.0'
  pod 'RxSwift', '6.5.0'
  pod 'Differ'
  
  pod 'FirebaseMessaging'
  
  pod 'Alamofire', '~> 5.6.4'
  pod 'Kingfisher', '~> 7.0'
  
  pod 'EasyPeasy', '~> 1.9.0'
  pod 'TLPhotoPicker', '~> 2.1.0'
  pod 'Localize-Swift', '~> 3.2'
 
	pod 'Parchment', '~> 3.2'
  pod 'CropViewController'
  pod 'MXParallaxHeader', '~> 1.1.0'
end
